- hosts: all
  sudo: true
  tasks:
    - name: add a new user      #Linuxユーザの作成
      user: name=khirano state=present

    - name: mkdir .ssh          #.sshフォルダの作成
      file: dest=/home/khirano/.ssh/ state=directory owner=khirano group=khirano mode=700

    - name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
      file: dest=/home/khirano/.ssh/authorized_keys state=touch owner=khirano group=khirano mode=600

    - name: copy publickey     #公開鍵を貼付け
      copy: src=/home/karuman/Downloads/id_rsa_khirano.pub dest=/home/khirano/.ssh/authorized_keys
